server:
  port: 8888
spring:
  application:
    name: cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/LYGit1/cloud-config-repo.git
#          searchPaths: cloud-config-repo
        native:
          search-locations: /Users/leiyi/Documents/configTest
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8761/eureka,http://peer1:8762/eureka